//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___PresenterInput {
    var output: ___FILEBASENAMEASIDENTIFIER___PresenterOutput!
    var router: ___FILEBASENAMEASIDENTIFIER___Router!
    weak var viewController: ___FILEBASENAMEASIDENTIFIER___ViewController?
    
    // MARK: ___FILEBASENAMEASIDENTIFIER___PresenterInput
}